#define CITY_DIMENSION 51
#define ANT_POPULATION 10
#define PHEROMONE_OF_ANT 10
#define DISTANCE_CONTROL_FACTOR 1
#define PHEROMONE_CONTROL_FACTOR 2
#define EVAPORATION_FACTOR 0.8 // between 0.8 ~ 0.9
#define MIN_PHEROMONE_AMOUNT 0.000167
#define ITERATION_COUNT 10