all: compile run

compile:
	g++ main.cpp -o main.exe

run:
	main.exe 1000 -4 4 2 20 -40 40 1 2 2 51
#	main.exe ITERATION V_LOWER_BOUND V_UPPER_BOUND X_DIM PTC_AMOUNT MAP_LOWER_BOUND MAP_UPPER_BOUND INERTIA_WEIGHT P_LEARNING_FACTOR G_LEARNING_FACTOR RUN

clean:
	del *.o *.exe